#! /bin/bash
# This script for starting ltalk server

cd build
if (($# < 1)); then
	sudo ./ltalks -r
	exit
fi
	
if [ $1 == "-b" ]; then
	sudo ./ltalks -r &
elif [ $1 == "-s" ]; then
	sudo ./ltalks -s
fi
